In [14]:
import numpy as np
arr1 = np.random.randint(11, size = (1,10))
print(f'Матрица 1: {arr1}')
arr2 = np.random.randint(11, size = (1,10))
print(f'Матрица 2: {arr2}')
arr3 = arr1+arr2
print(f'Сумма матриц: {arr3}')
arr3 = arr3.reshape((2,5))
print(arr3)
print(arr3.mean())

Матрица 1: [[ 2  5  4  4  7  6  1  4 10  8]]
Матрица 2: [[ 0  3  4  3 10  6  5  5 10  3]]
Сумма матриц: [[ 2  8  8  7 17 12  6  9 20 11]]
[[ 2  8  8  7 17]
 [12  6  9 20 11]]
10.0


In [22]:
arr1 = np.random.randint(15, size = (3,3))
print(arr1[0])
print(arr1[:,0:1])
arr1 = arr1.reshape(9,1)
print(arr1)
arr1 = arr1.flatten()
print(arr1)

[12  7  8]
[[12]
 [11]
 [ 3]]
[[12]
 [ 7]
 [ 8]
 [11]
 [ 1]
 [ 8]
 [ 3]
 [ 3]
 [12]]
[12  7  8 11  1  8  3  3 12]


In [28]:
arr1 = np.random.randint(1, 11, size=(4, 3))
print(arr1)
result = np.vstack((arr1[:, [0]], arr1[:, [1]], arr1[:, [2]]))
print(result)

[[ 3  6  3]
 [10  6  3]
 [ 1 10  9]
 [ 4  4  3]]
[[ 3]
 [10]
 [ 1]
 [ 4]
 [ 6]
 [ 6]
 [10]
 [ 4]
 [ 3]
 [ 3]
 [ 9]
 [ 3]]


In [32]:
arr1 = np.random.randint(1,31, size = 9)
print(arr1)
max_index = np.argmax(arr1)
print("Индекс максимального элемента:", max_index)
print("Максимальное значение:", arr1[max_index])

[13  7 20 25  1 24 24  7 17]
Индекс максимального элемента: 3
Максимальное значение: 25


In [39]:
arr1 = np.random.randint(1,6, size = (2,2))
arr2 = np.random.randint(1,6, size = (2,2))
print(f'Матрица 1: {arr1}')
print(f'Матрица 2: {arr2}')
tr = np.transpose(arr1)
print(f'Транспонированная матрица: {tr}')
print(f'Сложение матриц: {arr1 + arr2}')

Матрица 1: [[2 4]
 [3 4]]
Матрица 2: [[3 5]
 [4 4]]
Транспонированная матрица: [[2 3]
 [4 4]]
Сложение матриц: [[5 9]
 [7 8]]
